config/routes.rb
Rails.application.routes.draw do
  
  get '/shipping' => 'shipping#index'
  get '/finance' =>'finance#index'
  post '/approve/(:id)' => 'finance#approve_by_finance', as: :approve
  post '/err/(:id)' => 'finance#failure', as: :failure
  
  get    '/login' => 'login#new', as: :login
  post   '/login' => 'login#create'
  delete '/logout' => 'login#destroy', as: :logout
  
  match "/delayed_job" => DelayedJobWeb, :anchor => false, :via => [:get, :post]
  root 'orders#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/note.rb
class Note < ApplicationRecord
  belongs_to :order
end

app/models/order.rb
# == Schema Information
#
# Table name: orders
#
#  id           :integer          not null, primary key
#  order_id     :string
#  name         :string
#  email        :string
#  full_address :string
#  cc_num       :string
#  phone        :string
#  make         :string
#  model        :string
#  milage       :string
#  price        :decimal(, )
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#

class Order < ApplicationRecord
  include AASM
  validates :name, :email, :full_address, :cc_num, :phone, :make, :model, :milage, :price, presence: true

  has_many :notes, dependent: :destroy

  aasm do # default column: aasm_state
    state :created, :initial => true
    state :ready_for_payment
    state :payment_processed
    state :shipped
    state :failed

    event :finance_approve do
      transitions :from => :created, :to => :ready_for_payment
    end

    event :make_payment do
      transitions :from => :ready_for_payment, :to => :payment_processed
    end

    event :ship do
      transitions :from => :payment_processed, :to => :shipped
    end

    event :fail do
      transitions :to => :failed
    end

  end

  def used_car?
    milage.to_i > 0  
  end

  def add_note(text)
    Note.create(body: text, order_id: self.id)
  end

  def all_notes
    #notes.map{|n| n.body}.join(', ')
    notes.map(&:body).join(', ')
  end

end

app/models/user.rb
class User < ApplicationRecord
  validates :email, :role, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base


  def authenticate
    redirect_to '/login' unless current_user
  end

  def current_user
    User.find(session[:user_id]) if session[:user_id]
  end
  def check_role(role_name)
    current_user.role == role_name.to_s
  end

end

app/controllers/finance_controller.rb
class FinanceController < ApplicationController
  before_action :authenticate

  def index  
    check_role(:finance)  

    if params[:aasm_state]
      @orders = Order.where(aasm_state: params[:aasm_state])
    else
      @orders = Order.created
    end
  end

  def approve_by_finance
    order = Order.find(params[:id])
    order.finance_approve!
    redirect_to finance_path
  end
  
  def failure
    order = Order.find(params[:id])
    order.fail!
    redirect_to finance_path
  end
end

app/controllers/login_controller.rb
class LoginController < ApplicationController
  def new
  end
  
  def destroy
    session.delete(:user_id)
    redirect_to login_url
  end

  def create
    user = User.where(email: params[:email])[0]
    if user
      session[:user_id] = user.id
      redirect_to user_landing_page(user)
    else
      redirect_to login_url
    end
  end

  private
  def user_landing_page user
    case user.role
    when 'finance'
      '/finance'
    when 'delivery'
      '/shipping'
    else
      '/orders'
    end
  end
end

app/controllers/logins_controller.rb
class LoginsController < ApplicationController
  def new
  end
  
  def destroy
    session.delete(:user_id)
    redirect_to new_login_url
  end

  def create
    user = User.where(email: params[:email])[0]
    if user
      session[:user_id] = user.id
      redirect_to user_landing_page(user)
    else
      redirect_to new_login_url
    end
  end

  private
  def user_landing_page user
    case user.role
    when 'finance'
      '/finance'
    when 'delivery'
      '/delivery'
    else
      '/orders'
    end
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def index
    @orders = Order.all
  end
end

app/controllers/project.rb
class Project
  attr_accessor :name, :description
  def initialize name, description
    @name = name
    @description = description
  end
  def elevator_pitch
    "#{@name}, #{@description}"
  end
end

app/controllers/shipping_controller.rb
class ShippingController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_user_and_role

    user = User.find(session[:user_id]) if session[:user_id]

    if user && user.email
      "#{user.email.split('@').first.humanize} at #{user.role.humanize}"
    end
    
  end
end

app/helpers/shipping_helper.rb
module ShippingHelper
end

app/views/finance/index.html.erb
<!-- <h1>Finance Depts</h1>  -->
<div class='container'>
<td><%= link_to "Wating for Approval", finance_path(aasm_state: nil), class: "waves-effect orange btn"%></td>
<td><%= link_to "Approved Orders", finance_path(aasm_state: 'ready_for_payment'), class: "waves-effect green btn"%></td>
<td><%= link_to "Errors", finance_path(aasm_state: 'failed'), class: "waves-effect red btn"%></td>
<table>
  <tr>
    <th>customer</th>
    <th>cc_num</th>
    <th>car</th>
    <th>milage</th>
    <th>price</th>
    <th>errors</th>
  </tr>
  <% @orders.each do |order| %>
    <tr>
      <td><%=order.name %></td>
      <td><%=order.cc_num %></td>
      <td><%=order.make %>, <%=order.model %></td>
      <td><%=order.milage %></td>
      <td><%=order.price %></td>
      <%if order.aasm_state == 'created'%>
        <td><%= link_to "Approve", approve_path(order.id), class: "waves-effect green btn", method: 'post'%></td>
        <td><%= link_to "Decline", failure_path(order.id), class: "waves-effect waves-light btn", method:'post'%></td>
      <%elsif order.aasm_state == 'failed'%>
        <td><p class="red-text"><%= order.all_notes%></p> </td> 
      <%else%>
        <td><p class="green-text"><%= order.all_notes%></p> </td> 

      <%end%>
      </td>
    </tr>
  <% end %>
</table></div>

app/views/layouts/_nav.html.erb
<% if session[:user_id] %>
  <li><%= link_to 'logout',  logout_url, method: :delete %></li>
<%else%>
  <li><%= link_to 'login',  login_url %></li>
<%end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OrderProcessor</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    
    
    <nav class="darken-4" role="navigation">
      <div class="nav-wrapper container"><a id="logo-container" href="#" class="brand-logo">Order procssing</a>
        <ul class="right hide-on-med-and-down">
          <%= render partial: 'layouts/nav'%>          
        </ul>

        <ul id="nav-mobile" class="sidenav">
          <%= render partial: 'layouts/nav'%>
        </ul>
        <a href="#" data-target="nav-mobile" class="sidenav-trigger"><i class="material-icons">menu</i></a>

      </div>
    </nav>

    
    <div class='container'>
      <span class='right'><%= current_user_and_role %></span>
      <%= yield %>
    </div>
  </body>
</html>

app/views/login/create.html.erb
<h1>Login#create</h1>
<p>Find me in app/views/login/create.html.erb</p>

app/views/login/destroy.html.erb
<h1>Login#destroy</h1>
<p>Find me in app/views/login/destroy.html.erb</p>

app/views/login/new.html.erb
<form action="/login" method="post">
  Email <br/>
  <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
  <input type='text' name='email'/> <br/>
  <input type="submit" value="Login">
</form>

app/views/orders/index.html.erb
<table>
  <tr>
    <th>name</th>
    <th>email</th>
    <th>full_address</th>
    <th>cc_num</th>
    <th>phone</th>
    <th>make</th>
    <th>model</th>
    <th>milage</th>
    <th>price</th>
  </tr>
  <% @orders.each do |order| %>
    <tr>
      <td><%=order.name %></td>
      <td><%=order.email %></td>
      <td><%=order.full_address %></td>
      <td><%=order.cc_num %></td>
      <td><%=order.phone %></td>
      <td><%=order.make %></td>
      <td><%=order.model %></td>
      <td><%=order.milage %></td>
      <td><%=order.price %></td>
    </tr>
  <% end %>
</table>

app/views/shipping/index.html.erb
<h1>Orders ready to ship</h1>